# Generated by Django 5.2.5 on 2026-02-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0004_remove_chatroom_id_alter_chatroom_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
